# Generated by Django 5.0.1 on 2024-01-12 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_surveyquestions_question1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestions',
            name='question1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
