# Generated by Django 5.0.1 on 2024-01-14 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owlwatch', '0002_questions_average_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='average_frequency',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='average_intensity',
        ),
        migrations.CreateModel(
            name='Averages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_intensity', models.IntegerField(default=0)),
                ('average_frequency', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
